### ISSUE TITLE
Failed to wrap a class if the target class seems to have the method named "initialize"

### ISSUE THREAD

**Issue by cafedomancer** [mrkn/pycall#10]
I am creating the wrapper for [gensim](https://radimrehurek.com/gensim/index.html), and I have found some cases where the `wrap_class` fails to wrap a class. The example code is shown below.

```ruby
# script.rb
require "pycall"

tfidf_model = PyCall.import_module("gensim.models").TfidfModel

module Gensim
  module Models
    class TfidfModel
      include PyCall::PyObjectWrapper
      wrap_class PyCall.import_module("gensim.models").TfidfModel
    end
  end
end

p tfidf_model.([[[0, 1.0], [1, 1.0], [2, 1.0]],
                [[2, 1.0], [3, 1.0], [4, 1.0], [5, 1.0], [6, 1.0], [8, 1.0]],
                [[1, 1.0], [3, 1.0], [4, 1.0], [7, 1.0]],
                [[0, 1.0], [4, 2.0], [7, 1.0]],
                [[3, 1.0], [5, 1.0], [6, 1.0]],
                [[9, 1.0]],
                [[9, 1.0], [10, 1.0]],
                [[9, 1.0], [10, 1.0], [11, 1.0]],
                [[8, 1.0], [10, 1.0], [11, 1.0]]])
```

It goes like the following outputs.

```shell
cafedomancer@MacBook ~/.g/g/c/gensim.rb (master)> ruby script.rb 
/Users/cafedomancer/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170317/lib/pycall/pyobject.rb:12:in `getattr': undefined method `__pyobj__' for nil:NilClass (NoMethodError)
	from /Users/cafedomancer/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170317/lib/pycall/pyobject_wrapper.rb:32:in `block (2 levels) in wrap_class'
	from /Users/cafedomancer/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170317/lib/pycall/conversion.rb:86:in `new'
	from /Users/cafedomancer/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170317/lib/pycall/conversion.rb:86:in `block in to_ruby'
	from /Users/cafedomancer/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170317/lib/pycall/conversion.rb:14:in `each_type_pair'
	from /Users/cafedomancer/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170317/lib/pycall/conversion.rb:77:in `to_ruby'
	from /Users/cafedomancer/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170317/lib/pycall/conversion.rb:170:in `to_ruby'
	from /Users/cafedomancer/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170317/lib/pycall/pyobject_wrapper.rb:166:in `call'
	from script.rb:62:in `<main>'
```

When I read the documentation of gensim, I found that the Python class `gensim.models.tfidfmodel.TfidfModel` has the method named `initialize` (https://radimrehurek.com/gensim/models/tfidfmodel.html). Maybe I think the problem is caused by the target class which has the `initialize` method because it is special in Ruby classes, but I couldn't investigate it in depth.

**Comment by mrkn** [comment]
@cafedomancer Good catch.  Thank you for your report.

**Comment by mrkn** [comment]
This issue has been resolved in the current master branch.

```console
bash-3.2$ cat gensim_tfidf.rb
require 'pycall'

Gensim = PyCall.import_module('gensim')
Gensim::Models = Gensim.models
Gensim::Models::TfidfModel = Gensim.models.TfidfModel

p Gensim::Models::TfidfModel.new([
  [[0, 1.0], [1, 1.0], [2, 1.0]],
  [[2, 1.0], [3, 1.0], [4, 1.0], [5, 1.0], [6, 1.0], [8, 1.0]],
  [[1, 1.0], [3, 1.0], [4, 1.0], [7, 1.0]],
  [[0, 1.0], [4, 2.0], [7, 1.0]],
  [[3, 1.0], [5, 1.0], [6, 1.0]],
  [[9, 1.0]],
  [[9, 1.0], [10, 1.0]],
  [[9, 1.0], [10, 1.0], [11, 1.0]],
  [[8, 1.0], [10, 1.0], [11, 1.0]]
])
bash-3.2$ bundle exec ruby gensim_tfidf.rb
<gensim.models.tfidfmodel.TfidfModel object at 0x10670bc50>
```
