### ISSUE TITLE
keras from pycall

### ISSUE THREAD

**Issue by m-suketa** [mrkn/pycall#12]
I tried to use keras from pycall, but I encountered the error.

```ruby
require 'pycall/import'
include PyCall::Import
pyimport "keras"
```

The error is the following.
```
Using TensorFlow backend.
/home/ubuntu/.anyenv/envs/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170329/lib/pycall/eval.rb:35:in `import_module': pytype(AttributeError): AttributeError("module 'sys' has no attribute 'argv'",) (PyCall::PyError)
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/keras/activations.py", line 3, in <module>
    from . import backend as K
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/keras/backend/__init__.py", line 64, in <module>
    from .tensorflow_backend import *
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 118, in <module>
    from tensorflow.python.platform import app
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 23, in <module>
    from tensorflow.python.platform import flags
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 25, in <module>
    _global_parser = _argparse.ArgumentParser()
  File "/home/ubuntu/.anyenv/envs/pyenv/versions/anaconda3-4.3.1/lib/python3.6/argparse.py", line 1622, in __init__
    prog = _os.path.basename(_sys.argv[0])
        from /home/ubuntu/.anyenv/envs/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170329/lib/pycall/import.rb:24:in `pyimport'
        from test_keras.rb:3:in `<main>'
```

How can I fix this error?
Is this the issue of pycall ?
or, Is there any workaround of the error?

The Ruby version is 2.4.1p111
The Python version is 3.6.0 :: Anaconda 4.3.1
The Keras version is 2.0.2
The tensorflow version is 1.0.1

**Comment by m-suketa** [comment]
I'm not sure, but this issue because of not calling `PySys_SetArgvEx` .

There is no error by calling `PySys_SetArgvEx` like as follows. 
(Yes, it is not correct..., but I don't know how to set arguments of PySys_SetArgvEx correctly.)

```ruby
require 'pycall/import' 

module PyCall 
  module LibPython 
    attach_function :PySys_SetArgvEx, [:int, :buffer_in, :int], :void 
  end  
end

strptrs = []
strptrs << FFI::MemoryPointer.from_string("")

argv = FFI::MemoryPointer.new(:pointer, strptrs.length)
strptrs.each_with_index do |p, i|
  argv[i].put_pointer(0,  p)
end

# PyCall:LibPython.PySys_SetArgvEx(1, argv, 0) does not work. Fatal Python Error occurred.
PyCall::LibPython.PySys_SetArgvEx(0, argv, 0)

include PyCall::Import 

pyimport "keras" 
```

Are you planning to provide `PySys_SetArgvEx` functionality in pycall?

**Comment by mrkn** [comment]
@m-suketa thank you for your report.
Please use the version >= 0.1.0.alpha.20170403.
