### ISSUE TITLE
wrap_class doesn't work for pandas.DataFrame

### ISSUE THREAD

**Issue by mrkn** [mrkn/pycall#16]
```ruby
require 'pycall'

module Pandas
  class DataFrame
    include PyCall::PyObjectWrapper
    wrap_class PyCall.import_module('pandas').DataFrame
  end
end
```

This code doesn't work properly.

```console
$ ruby pandas.rb
/Users/mrkn/src/github.com/mrkn/pycall/lib/pycall/pyobject.rb:16:in `getattr': pytype(AttributeError): AttributeError("'NoneType' object has no attribute '_data'",) (PyCall::PyError)
  File "pandas/src/properties.pyx", line 61, in pandas.lib.AxisProperty.__get__ (pandas/lib.c:46146)
        from /Users/mrkn/src/github.com/mrkn/pycall/lib/pycall/pyobject_wrapper.rb:27:in `block in wrap_class'
        from /Users/mrkn/src/github.com/mrkn/pycall/lib/pycall/list.rb:55:in `each'
        from /Users/mrkn/src/github.com/mrkn/pycall/lib/pycall/pyobject_wrapper.rb:26:in `wrap_class'
        from -:6:in `<class:DataFrame>'
        from -:4:in `<module:Pandas>'
        from -:3:in `<main>'
```

**Comment by mrkn** [comment]
```
bash-3.2$ bin/console
[1] pry(main)> pd = PyCall.import_module('pandas')
=> <module 'pandas' from '/Users/mrkn/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/__init__.py'>
[2] pry(main)> pd.DataFrame.new(data: { a: [1, 2, 3, 4, 5], b: ['x', 'y', 'z', 'z', 'y'] })
=>    a  b
0  1  x
1  2  y
2  3  z
3  4  z
4  5  y
[3] pry(main)> pd.DataFrame
=> <class 'pandas.core.frame.DataFrame'>
[4] pry(main)> pd.DataFrame.class
=> Class
[5] pry(main)>
```
